In [2]:
import numpy as np


Dimensions in Arrays


1-d array


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2-d array

In [4]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


3-d Array

In [6]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


NumPy Array Indexing

In [ ]:
# 1-d Array
arr = np.array([1,2,3,4,5])
print(arr[0])

# 2-d Array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("i am arr2",arr[0])

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("i am arr3",arr[0,2])

# 3-d Array
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print("i am arr4",arr[1,0,2])


1
i am arr2 [1 2 3 4 5]
i am arr3 3
i am arr4 11
[[ 3  7]
 [11 15]]


NumPy Array Slicing

In [43]:
# 1-d Array
arr = np.array([1,2,3,4,5])
print(arr[:3])

arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[:-5])


# 2-d Array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,0:4])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("i am ",arr[0:2,2])


# 3-d Array
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr[1,:2,1])


[1 2 3]
[1 2 3 4]
[1 2 3 4]
i am  [3 8]
[10 14]
