Numpy Datatype


In [ ]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )


checking datatype in numpy

In [4]:
import numpy as np

In [17]:
arr = np.array([1,2,3,4,5,6])
print(arr.dtype)

arr = np.array(["name","address"])
print(arr.dtype)

arr = np.array([1,2,3,4,5,6], dtype='S')
print(arr.dtype)
print(arr)

arr = np.array([1,2,3,4,5,6], dtype='F')
print(arr.dtype)
print(arr)

arr = np.array([1,2,3,4,5,6], dtype='i4')
print(arr.dtype)
print(arr)




int64
<U7
|S1
[b'1' b'2' b'3' b'4' b'5' b'6']
complex64
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]
int32
[1 2 3 4 5 6]


Converting Data Type 

In [ ]:
arr = np.array([1,2,3,4,5])
newarr = arr.astype('S')
print(newarr)

arr = np.array([1,2,3,4,5])
newarr = arr.astype('F')
print(newarr)

arr =np.array([1.2,2.0,3.9])
newarr = arr.astype('i')
print(arr)
print(newarr)

arr = np.array([1,0,1,0,2])
newarr =arr.astype(bool)
print(newarr)





[b'1' b'2' b'3' b'4' b'5']
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
[1.2 2.  3.9]
[1 2 3]
[ True False  True False  True]


Numpy copy and view array

In [47]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


checking orginal data 

In [49]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


Shape of an Array

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)



arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]],ndmin=3)
print(arr)
print(arr.shape)




(2, 4)
<built-in method reshape of numpy.ndarray object at 0x1265b1bf0>
[[[1 2 3 4]
  [5 6 7 8]]]
(1, 2, 4)


Reshaping arrays

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,3,2)
print(newarr)
print(arr.ndim)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)
print(newarr)
print(newarr.ndim)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)


arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
newarr = arr.reshape(-1)
print(newarr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
