Numpy array iterating

In [60]:
import numpy as np

In [7]:
arr =np.array([1,2,3])
for i in arr:
    print(i)
    
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    print(i)
    
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    for j in i:
        print(j)
        
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for i in arr:
    for j in i:
        for x in j:
            print(x)

        

1
2
3
[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


using uditer()

In [ ]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


changing datatype during iteration

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(i)
    
    

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')


Iterating With Different Step Size

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:,1::2]):
    print(x)

arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for x in np.nditer(arr[:,:,0]):
    print(x)
    
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:,1:]):
    print(x)  


2
4
6
8
1
5
9
13
2
3
4
6
7
8


Numpy joining array

Iteration Using ndenumerate()

using concatenate

In [16]:


arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)
  
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


NumPy Joining Array

In [28]:
# 1-d array joining
arr1 =np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

# 2-d array joining
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

# 3-d array joining
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])
arr = np.concatenate((arr1, arr2),axis=2)
print(arr)




[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2 5 6]
  [3 4 7 8]]]


stacking arrays

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2),axis=1)
print(arr)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.stack((arr1, arr2),axis=1)
print(arr)

arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])
arr = np.stack((arr1, arr2))
print(arr)


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)




[[1 4]
 [2 5]
 [3 6]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


Splitting NumPy Arrays

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)



[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


NumPy Searching Arrays

In [48]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

arr =np.array([1,2,3,4,5,6,7,8,9,10.11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
x = np.where(arr%3==0)
print(x)



(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)
(array([ 2,  5,  8, 10, 13, 16, 19, 22, 25, 28]),)


Search Sorted array

In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.searchsorted(arr,2)
print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.searchsorted(arr,2,side='right')
print(x)

arr = np.array([1, 3, 4,  6, 7, 8])
x = np.searchsorted(arr,[2,5,9])
print(x)



1
2
[1 3 6]


NumPy Sorting Arrays

In [ ]:
arr = np.array([True, False, True])
print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))




[False  True  True]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]


NumPy Filter Array