In [2]:
import numpy as np

create a 4*4 matrix where row is [1,2,3,4]


In [9]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Given arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), extract the sub-array [[2, 3], [5, 6]] using slicing.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:2,1:])

[[2 3]
 [5 6]]


Convert an array [1.5, 2.5, 3.5] to integers without rounding (truncate decimals).

In [17]:
arr =np.array([1.2,2.5,3.5])
print(arr.astype('i'))

[1 2 3]


Create a view of an array arr = np.array([10, 20, 30]) and modify the view. Show that the original array changes.

In [19]:
arr = np.array([10, 20, 30])
newarr = arr.view()
arr[2]=15
print(newarr)
print(arr)

[10 20 15]
[10 20 15]


Reshape a 1D array [1, 2, 3, 4, 5, 6, 7, 8] into a 3D array of shape (2, 2, 2).

In [21]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Iterate over a 2D array [[1, 2], [3, 4]] and multiply each element by 2 without using loops.

In [26]:
arr = np.array([[1,2],[3,4]])
mul = arr *2
print(mul)

[[2 4]
 [6 8]]


Stack two 1D arrays [1, 2, 3] and [4, 5, 6] column-wise to create a 2x3 matrix.

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.vstack((arr1,arr2))
print(newarr)

[[1 2 2]
 [4 5 6]]


Split a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] into 3 equal sub-arrays along rows.

In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


Find all indices in the array [5, 10, 15, 20, 15, 10, 5] where elements are greater than 12.

In [32]:
arr = np.array([5, 10, 15, 20, 15, 10, 5])
newarr =np.where(arr>12)
print(newarr)


(array([2, 3, 4]),)


Filter the array [1, 2, 3, 4, 5, 6] to return elements that are even or greater than 4.

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])

result = arr[(arr%2==0)|(arr>4)]
print(result)

[2 4 5 6]


Convert a 1D array of 12 elements into a 2x2x3 3D array.

In [38]:
arr = np.arange(1,13)
print(arr.reshape(2,2,3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Replace all negative values in the array [-1, 2, -3, 4, -5] with 0.

In [4]:
arr = np.array([[-1, 2, -3, 4, -5]])
arr[arr<0]=0
print(arr)

[[0 2 0 4 0]]


Reverse the rows of a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9]].


In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr=arr[::-1]
print(newarr)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


Create a structured array with fields name (string) and age (integer) for 3 people.

In [7]:
arr = np.dtype([('name','U20'),('age','i4')])
newarr =np.array([('Nishan',24),('xatra',25)],dtype=arr)
print(newarr)
print(newarr['name'])
print(newarr['age'])

[('Nishan', 24) ('xatra', 25)]
['Nishan' 'xatra']
[24 25]


Compute the dot product of matrices [[1, 2], [3, 4]] and [[5, 6], [7, 8]].

In [ ]:
arr1=np.array([[1, 2], [3, 4]])
arr2 =np.array([[5, 6], [7, 8]])
newarr=arr1*arr2
print(newarr)

[[ 5 12]
 [21 32]]


Concatenate two arrays [[1, 2], [3, 4]] and [[5, 6]] vertically

In [ ]:
arr1 =np.array([[1,2],[3,4]])
arr2 =np.array[[5,6]]
newarr = np.concatenate((arr1,arr2),axis=0)
print(newarr)

[[1 2]
 [3 4]
 [5 6]]


Find the unique rows in a 2D array [[1, 2], [3, 4], [1, 2], [5, 6]].

In [12]:
arr =np.array([[1, 2], [3, 4], [1, 2], [5, 6]])
newarr = np.unique(arr,axis=0)
print(newarr)

[[1 2]
 [3 4]
 [5 6]]
