In [4]:
import numpy as np

Random Numbers in NumPy

In [ ]:
from numpy import random


arr = random.randint(100)
print(arr)

arr = random.rand()
print(arr)

arr = random.randint(100,size=2)
print(arr)

arr = random.randint(100,size=(3,5))
print(arr)

arr = random.rand(3,5)
print(arr)


x = random.choice([3, 5, 7, 9])
print(x)

x = random.choice([3, 5, 7, 9],size=(3,5))
print(x)







40
0.37396195629756135
[67 22]
[[72 16 33 88  3]
 [ 9 40 93 83 52]
 [68 99 92  7 10]]
[[0.99774165 0.75928102 0.70101792 0.50058265 0.1464684 ]
 [0.08995368 0.93912582 0.04440719 0.35306852 0.23398666]
 [0.08661608 0.56258683 0.69440351 0.55084772 0.92671626]]
3
[[5 9 9 7 5]
 [5 3 3 3 3]
 [3 7 3 9 5]]


Data distrubution 

In [95]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.1, 0.5])
print(x)

arr = np.array([1,2,3,4,5])
x = random.shuffle(arr)

print(arr)

arr = np.array([1,2,3,4,5,6])
x = random.permutation(arr)

print(arr)

5
[1 4 5 3 2]
[1 2 3 4 5 6]
