# example of linear equation
# 2x + y = 5,
# x - y = 1

In [19]:
import numpy as np  
a = np.array([[2,1],[1,-1]])
b = np.array([5,1])
sol = np.linalg.solve(a,b)
print(sol)


[2. 1.]


# 3x + y-2z =9
# 2x -y + z = 3
# x +2y +3z =12

In [20]:
a = np.array ([[3,1,-2],[2,-1,1],[1,2,3]])
b = np.array([9,3,12])
sol = np.linalg.solve(a,b)
print(sol)

[2.6 3.2 1. ]


In [14]:
import numpy as np 
a = np.random.random(1000000)
a

array([0.7003436 , 0.84540099, 0.15662896, ..., 0.80646166, 0.28407041,
       0.20751888], shape=(1000000,))

In [15]:
%%time
x= np.sum(a)

CPU times: user 1.31 ms, sys: 1.04 ms, total: 2.35 ms
Wall time: 5.89 ms


In [16]:
%%time
x=0
for element in a:
    x += element

CPU times: user 97 ms, sys: 1.97 ms, total: 99 ms
Wall time: 102 ms


In [17]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

b = a[1:4, 2:4]
print(b)

c = a[0:2, 1:3]
print(c)



[[ 7  8]
 [11 12]]
[[2 3]
 [6 7]]


In [18]:
import numpy as np 
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[:,0:2])

a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a[:,2:4])

a = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(a[:,2:3,0])



[[1 2]
 [6 7]]
[[ 3  4]
 [ 8  9]
 [13 14]]
[]


# Random number

In [54]:
# generate single random number between 0 and 1
import numpy as np
number= np.random.rand()
print(number)

#generate a single random interger between 0 and 10
import numpy as np
number= np.random.randint(0,10,size =5)
print(number)

#generate a 3x2 array of random integer between 0 and 20
import numpy as np
number= np.random.randint(0,20,size =(3,2))
print(number)

#randomly choose 3 element from the list[1,2,3,4,5]
import numpy as np
number= np.random.choice([1,2,3,4,5],size =3)
print(number)


#sample with replacement (the same element can be choosen more than once )
import numpy as np
number= np.random.choice([1,2,3,4,5],size =3, replace =False)
print(number)

0.5016209763100709
[4 7 7 6 8]
[[ 2 13]
 [10 14]
 [13  3]]
[2 4 2]
[4 1 2]


# Random number with a specific seed

In [78]:
a =np.random.seed(42)
number= np.random.rand()
print(number)
a =np.random.seed(40)
number= np.random.rand()
print(number)

0.3745401188473625
0.4076870280802861
