# Numpy exerice

In [4]:
import numpy as np

## Given are 2 similar dimensional numpy arrays perform element wise addition


[1 2 3]
[4 5 6]

[10 11 12]
[13 14 15]

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,11,12],[13,14,15]])

newarr = a + b
print(newarr)

[[11 13 15]
 [17 19 21]]


## Multiply the following matrix with a scalar 2

[1 2 3]
[4 5 6]

In [3]:
a = np.array([[1,2,3],[4,5,6]])
newarr = a * 2
print(newarr)

[[ 2  4  6]
 [ 8 10 12]]


## Create a identiy matrix of 4X4

[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]

In [9]:
arr = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Construct a 1D array and reshape to 3D array 3X3X shape



In [33]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14],[15,16,17],[18,19,20],[21,22,23],[24,25,26]])
newarr =arr.reshape(-1)
print(newarr)

b = arr.reshape(3,3,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


## Convert all the elements of a numpy array from float to integer datatype. Hint: use astype

In [34]:
arr = np.array([[2.5,3.8,1.5],[4.7,2.9,1.56]])
newarr = arr.astype('i')
print(newarr)

[[2 3 1]
 [4 2 1]]


## Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array: i.e. to True, False

In [36]:
arr = np.array([[1,0,0],[1,1,1],[0,0,0]])
newarr =arr.astype(bool)
print(newarr)

[[ True False False]
 [ True  True  True]
 [False False False]]


## Horizontally stack the following matrix

In [43]:
arr1 = np.array([[[1,2,3],[5,6,7]],[[8,9,10],[11,12,13]]])
newarr=np.hstack(arr1)
print(newarr)

[[ 1  2  3  8  9 10]
 [ 5  6  7 11 12 13]]


## Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers: Hint use np.arrange



In [44]:
arr= np.arange(0,101,2)
print(arr)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


## Write a NumPy program that creates a large 1D array using np.random.rand and write a function to calculate the sum of its elements using a for loop. Then, optimize it using NumPy's built-in functions.

In [55]:
arr = np.random.rand(5)
print(arr)
a = 0
for i in arr:
    a += i
    print(a)
    
newarr = np.sum(arr)
print(newarr)

[0.92167939 0.90171185 0.84319358 0.73396744 0.56381046]
0.9216793882367169
1.8233912340902187
2.6665848176994
3.4005522588965436
3.9643627226849913
3.9643627226849913


## From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match [1,2,3,4,5] and [1,3,2,4,5]

In [58]:
arr1 =np.array([1,2,3,4,5])
arr2 = np.array([1,3,2,4,5])
newarr = np.where (arr1==arr2)[0]
print(newarr)

[0 3 4]


## Output a sequence of equally gapped 5 numbers in the range 0 to 100 Output: [  0.  25.  50.  75. 100.]

In [61]:
arr = np.linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


## Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

In [63]:
arr = np.full((2,3),5)
print(arr)

[[5 5 5]
 [5 5 5]]


## Output a 5-by-5 array of random integers between 0 and 10

In [65]:
arr = np.random.randint(0,10,size=(5,5))
print(arr)


[[3 9 0 4 0]
 [8 6 6 2 1]
 [4 5 6 3 9]
 [9 0 7 0 1]
 [7 5 3 3 3]]


## construct a 2X3 random matrix and transpose it

In [70]:
arr = np.random.rand(2,3)
print("orginal arr",arr)

newarr = arr.T
print("this is newarry",newarr)

orginal arr [[0.6946101  0.01708845 0.84023144]
 [0.49064506 0.01677738 0.40639411]]
this is newarry [[0.6946101  0.49064506]
 [0.01708845 0.01677738]
 [0.84023144 0.40639411]]


## convert dictionary {0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216} to array

In [72]:
d = {0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216} 
arr = np.array(list(d.values()))
print(arr)

[  0   1   8  27  64 125 216]


## Solve the Following Equation

3x + y - 2z = 9,
2x - y + z = 3,
x + 2y + 3z = 12

In [73]:
arr1=np.array([[3,1,-2],[2,-1,1],[1,2,3]])
arr2 =np.array([9,3,12])
newarr = np.linalg.solve(arr1,arr2)
print(newarr)

[2.6 3.2 1. ]


## Write a NumPy program to create a 3x3x3 array with random values and flatten it to a 1D array.

In [77]:
arr = np.random.rand(3,3,3)
print(arr)
newarr = arr.flatten()
print(newarr)

[[[0.5126715  0.26719812 0.26657561]
  [0.1065258  0.40376872 0.29556333]
  [0.76460347 0.5566649  0.62021778]]

 [[0.96713859 0.33671454 0.5830509 ]
  [0.84514475 0.22436663 0.93036966]
  [0.85391481 0.88485706 0.82662899]]

 [[0.92250385 0.30535074 0.39619407]
  [0.86056202 0.18963935 0.15594977]
  [0.62242244 0.82823788 0.33578465]]]
[0.5126715  0.26719812 0.26657561 0.1065258  0.40376872 0.29556333
 0.76460347 0.5566649  0.62021778 0.96713859 0.33671454 0.5830509
 0.84514475 0.22436663 0.93036966 0.85391481 0.88485706 0.82662899
 0.92250385 0.30535074 0.39619407 0.86056202 0.18963935 0.15594977
 0.62242244 0.82823788 0.33578465]


## Write a NumPy program to create a 3x3 array with random values and calculate the pairwise Euclidean distance between each pair of rows.

In [ ]:

arr = np.random.rand(3, 3)
print(arr)




## Load an Image using PIL and convert to numpy array.

In [ ]:
from PIL import Image
 
img =Image.open("image.jpeg")
print(img)

arr = np.array(img)
print(arr)

new = img.convert("L")
print(new)


<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=3024x4032 at 0x107ED8D60>
[[[ 81  79  66]
  [ 84  82  69]
  [ 84  82  69]
  ...
  [ 86  83  76]
  [ 87  84  77]
  [ 88  85  78]]

 [[ 82  80  67]
  [ 86  84  71]
  [ 86  84  71]
  ...
  [ 87  84  77]
  [ 88  85  78]
  [ 88  85  78]]

 [[ 84  82  69]
  [ 88  86  73]
  [ 88  86  73]
  ...
  [ 89  86  79]
  [ 89  86  79]
  [ 88  85  78]]

 ...

 [[172 135  90]
  [181 144  99]
  [203 166 121]
  ...
  [211 168 134]
  [209 166 132]
  [207 164 130]]

 [[179 145  99]
  [194 160 114]
  [218 184 138]
  ...
  [210 167 133]
  [208 165 131]
  [207 164 130]]

 [[199 167 120]
  [213 181 134]
  [233 199 153]
  ...
  [205 162 128]
  [204 161 127]
  [204 161 127]]]
<PIL.Image.Image image mode=L size=3024x4032 at 0x107EADA90>


TypeError: 'JpegImageFile' object is not subscriptable